/**
 * Registry identifier for the AI DevKit built-in skills.
 */
export const BUILTIN_SKILL_REGISTRY = 'codeaholicguy/ai-devkit';

/** Registry IDs shipped in the default registry snapshot used for offline protection. */
export const DEFAULT_SKILL_REGISTRY_IDS = new Set([
  BUILTIN_SKILL_REGISTRY,
  'CloudAI-X/claude-workflow-v2',
  'HeyVincent-ai/agent-skills',
  'SawyerHood/dev-browser',
  'Shopify/Shopify-AI-Toolkit',
  'WordPress/agent-skills',
  'addyosmani/agent-skills',
  'addyosmani/web-quality-skills',
  'adithya-s-k/manim_skill',
  'affaan-m/everything-claude-code',
  'analogjs/angular-skills',
  'antfu/skills',
  'anthropics/skills',
  'apify/agent-skills',
  'atxp-dev/cli',
  'boristane/agent-skills',
  'brianlovin/claude-config',
  'browser-use/browser-use',
  'callstackincubator/agent-skills',
  'cloudai-x/threejs-skills',
  'cloudflare/skills',
  'coreyhaines31/marketingskills',
  'dbt-labs/dbt-agent-skills',
  'dgreenheck/webgpu-claude-skill',
  'figma/mcp-server-guide',
  'firecrawl/cli',
  'forrestchang/andrej-karpathy-skills',
  'github/awesome-copilot',
  'giuseppe-trisciuoglio/developer-kit',
  'google-gemini/gemini-skills',
  'google-labs-code/stitch-skills',
  'google/skills',
  'huggingface/skills',
  'hyf0/vue-skills',
  'ibelick/ui-skills',
  'inference-sh/skills',
  'intellectronica/agent-skills',
  'itsmostafa/aws-agent-skills',
  'jeffallan/claude-skills',
  'jezweb/claude-skills',
  'jimliu/baoyu-skills',
  'kepano/obsidian-skills',
  'lackeyjb/playwright-skill',
  'mcollina/skills',
  'microsoft/agent-skills',
  'microsoft/playwright-cli',
  'muratcankoylan/Agent-Skills-for-Context-Engineering',
  'napoleond/clawdirect',
  'obra/superpowers',
  'onmax/nuxt-skills',
  'othmanadi/planning-with-files',
  'pluginagentmarketplace/custom-plugin-java',
  'remotion-dev/skills',
  'resciencelab/opc-skills',
  'resend/react-email',
  'samber/cc-skills-golang',
  'sickn33/antigravity-awesome-skills',
  'simonwong/agent-skills',
  'softaworks/agent-toolkit',
  'stripe/ai',
  'subsy/ralph-tui',
  'supabase/agent-skills',
  'superdesigndev/superdesign-skill',
  'vercel-labs/agent-browser',
  'vercel-labs/agent-skills',
  'vercel-labs/next-skills',
  'vercel-labs/skills',
  'vercel/ai',
  'vercel/turborepo',
  'vuejs-ai/skills',
  'vueuse/skills',
  'waynesutton/convexskills',
  'zackkorman/skills',
]);

/**
 * Canonical list of built-in skills that ship with AI DevKit. Keep in sync
 * with the skills published under the {@link BUILTIN_SKILL_REGISTRY}
 * registry. Commands that need to install or reference the curated set
 * (e.g., `ai-devkit init`, future `doctor`/`upgrade` commands) should import
 * from here rather than hard-coding names locally.
 */
export const BUILTIN_SKILL_NAMES = [
  'agent-communication',
  'agent-management',
  'dev-commit',
  'dev-lifecycle',
  'dev-worktree',
  'dev-requirements',
  'dev-design',
  'dev-planning',
  'dev-implementation',
  'dev-testing',
  'dev-review',
  'dev-pr',
  'structured-debug',
  'document-code',
  'memory',
  'task',
  'simplify-implementation',
  'brainstorm',
  'verify',
  'tdd'
] as const;

export type BuiltinSkillName = typeof BUILTIN_SKILL_NAMES[number];
